backend:
  name: github
  repo: ozkan/ozkan.github.io # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
  commit_messages: # Optional: configure the commit messages Netlify CMS will use when publishing changes
    create: "feat({{collection}}): :sparkles: Create {{slug}}"
    update: "chore({{collection}}): :recycle: Update {{slug}}"
    delete: "chore({{collection}}): :recycle: Delete {{slug}}"
    uploadMedia: "feat(assets): :bento: Upload {{path}}"
    deleteMedia: "chore(assets): :wastebasket: Delete {{path}}"

media_folder: 'assets/img'
logo_url: 'https://ozkancelik.com/assets/img/ozkancelik.png'
publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Header Photo', name: 'img', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Published', name: 'published', widget: 'boolean', default: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Manual PDF"
        name: "manual_pdf"
        widget: "file"
        required: false
        default: "/uploads/general-manual.pdf"
        media_library:
          config:
            multiple: true
      - { label: 'Color', name: 'color', widget: 'color', required: false  }
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/test.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: 'name', widget: string}
              - {label: Year, name: year, widget: string}
              - {label: Title, name: title, widget: string}
              - {label: Purpose, name: purpose, widget: string}
              - {label: Pdf, name: pdf, widget: string}
              - {label: Profile image, name: profile_img, widget: image}
              - {label: Thesis Type, name: thesis_type, widget: string}
              - {label: Graduated, name: graduated, widget: boolean}

  - name: "settings"
    label: "Settings"
    format: "frontmatter"
    editor:
      preview: false
    files:
      - name: "raw"
        label: "Raw File"
        file: "_data/bibtex.bib"
        fields:
          - {label: "Content", name: "body", widget: "text"}


  - name: "bibtex"
    label: "Bibtex"
    folder: '_bibliography/'
    format: "frontmatter"
    editor:
      preview: false
    fields:
      - {label: "Content", name: "body", widget: "text"}






# {label: “Categories”, name: “categories”, widget: “select”, options: [“Audax”, “Casuual/Family Ride”, “Cyclocross”, “Fixed”, “Group Ride”, “Sportive”]}


# - label: "Manual PDF"
#   name: "manual_pdf"
#   widget: "file"
#   default: "/uploads/general-manual.pdf"
#   media_library:
#     config:
#       multiple: true